(() => {
  'use strict';
  const $ = (s, p = document) => p.querySelector(s);
  const $$ = (s, p = document) => [...p.querySelectorAll(s)];
  const clamp = (v, min, max) => Math.min(max, Math.max(min, v));
  const pick = (arr, seed, offset = 0) => arr[Math.abs(seed + offset) % arr.length];
  const store = { get: (k, d) => { try { return JSON.parse(localStorage.getItem(k)) ?? d; } catch { return d; } }, set: (k, v) => localStorage.setItem(k, JSON.stringify(v)) };

  const moods = [
    ['luxury','Luxury','Quiet confidence and precise refinement',52,38,24,72,'neutral accent','editorial serif','elegant monogram','slow reveal'],
    ['calm','Calm','Soft focus, balance and open space',178,35,36,82,'analogous','humanist sans','minimal symbol','slow float'],
    ['storm','Storm','Electric tension and atmospheric depth',218,48,18,68,'split complementary','condensed sans','angular mark','brutal snap'],
    ['sunrise','Sunrise','Optimism, warmth and new momentum',28,82,42,88,'analogous','friendly sans','radiant symbol','fade in'],
    ['forest','Forest','Grounded, natural and quietly enduring',126,43,20,70,'analogous','humanist serif','organic symbol','soft scale'],
    ['cyber','Cyber','Digital energy and sharp precision',284,84,32,72,'complementary','monospace','modular glyph','pulse glow'],
    ['brutal','Brutal','Direct, raw and intentionally unpolished',8,76,16,84,'complementary','grotesk sans','heavy wordmark','brutal snap'],
    ['minimal','Minimal','Essential, clear and highly functional',210,12,25,92,'monochrome','neo-grotesk','reduced symbol','fade in'],
    ['playful','Playful','Bright, curious and pleasantly unexpected',322,72,40,88,'triadic','rounded sans','character mark','soft scale'],
    ['vintage','Vintage','Tactile nostalgia with storied character',32,43,24,76,'split complementary','old-style serif','heritage badge','fade in'],
    ['editorial','Editorial','Cultured contrast and visual intelligence',354,25,16,88,'neutral accent','high-contrast serif','wordmark','slide up'],
    ['fintech','Fintech','Trust, speed and confident clarity',204,72,28,78,'analogous','geometric sans','precise monogram','hover lift'],
    ['organic','Organic','Human warmth and natural irregularity',92,38,26,78,'analogous','soft serif','handmade symbol','slow float'],
    ['neon','Neon','High-voltage expression after dark',305,94,38,72,'triadic','display sans','luminous glyph','pulse glow'],
    ['desert','Desert','Sun-baked restraint and earthy calm',24,48,30,82,'analogous','warm serif','abstract landscape','fade in'],
    ['ocean','Ocean','Fluid depth, clarity and exploration',194,68,22,82,'analogous','humanist sans','wave symbol','slow float'],
    ['clay','Clay','Crafted, tactile and warmly imperfect',14,44,26,80,'neutral accent','soft grotesk','sculpted mark','soft scale'],
    ['glass','Glass','Airy transparency and future polish',188,54,56,94,'analogous','light sans','prismatic symbol','fade in'],
    ['monochrome','Monochrome','Disciplined reduction and strong hierarchy',0,6,12,92,'monochrome','grotesk sans','pure wordmark','slide up'],
    ['pastel','Pastel','Gentle optimism and approachable softness',268,52,68,92,'triadic','rounded sans','soft abstract mark','soft scale'],
    ['cinematic','Cinematic','Dramatic scale and immersive atmosphere',224,52,14,66,'split complementary','display serif','iconic emblem','slow reveal'],
    ['elegant','Elegant','Graceful proportion and timeless poise',330,30,30,86,'analogous','high-contrast serif','fine monogram','fade in'],
    ['dark','Dark','Focused, mysterious and uncompromising',250,34,8,54,'monochrome','condensed sans','negative-space mark','pulse glow'],
    ['warm','Warm','Inviting, generous and distinctly human',18,62,32,84,'analogous','friendly serif','welcoming symbol','soft scale']
  ].map(([id,label,description,hue,sat,minL,maxL,harmony,font,logo,animation]) => ({id,label,description,hue,sat,minL,maxL,harmony,font,logo,animation,keywords:[id,description.split(' ')[0].toLowerCase(),'brand']}));
  const harmonyLabels = ['analogous','complementary','triadic','split complementary','monochrome','neutral accent'];
  const harmonyOffsets = {
    'analogous':[-32,-16,0,16,32,48], 'complementary':[0,18,180,198,0,180], 'triadic':[0,120,240,18,138,258],
    'split complementary':[0,150,210,18,168,228], 'monochrome':[0,0,0,0,0,0], 'neutral accent':[0,0,0,180,0,0]
  };
  const i18n = {en:{}};
  Object.assign(i18n, {
    es:{...i18n.en,navPalette:'Paleta',navNaming:'Nombres',navSlogan:'Eslogan',navFonts:'Fuentes',navTokens:'Espaciado y sombras',navAnimations:'Animaciones',navMoodboard:'Moodboard',navLogo:'Prompt de logotipo',navBrandbook:'Manual de marca',privateNote:'Privado por diseño. Todo funciona en tu navegador.',save:'Guardar',step1:'PASO 01 — BASE',paletteTitle:'Convierte una sensación en color.',paletteSub:'Escribe una palabra o extrae colores de una imagen. La misma entrada siempre crea el mismo sistema.',wordMode:'Palabra a color',photoMode:'Foto a color',wordLabel:'Palabra o idea de marca',generate:'Generar sistema',tryLabel:'Prueba:',uploadTitle:'Arrastra una imagen o elige un archivo',uploadSub:'PNG, JPG o WEBP. Nunca sale de tu dispositivo.',generatedPalette:'Paleta generada',regenerate:'Regenerar desbloqueados',harmony:'Armonía',history:'Paletas guardadas',historySub:'Guardadas solo en este navegador.',clear:'Borrar todo',namingTitle:'Nombres con la temperatura adecuada.',namingSub:'Veinte ideas deterministas creadas con tu palabra, ambiente e industria.',refresh:'Nuevas ideas',industry:'Industria',sloganTitle:'Dilo en una línea.',sloganSub:'Esloganes creados con plantillas para tu dirección de marca.',fontsTitle:'Una voz que puedes ver.',fontsSub:'Combinaciones de fuentes del sistema para el ambiente actual.',tokensTitle:'Ritmo, forma y profundidad.',tokensSub:'Tokens de interfaz adaptados al ambiente de tu marca.',copyCss:'Copiar CSS',spacing:'Escala de espaciado',radius:'Escala de radios',shadows:'Sombras',animationsTitle:'Movimiento con personalidad.',animationsSub:'Previsualiza y copia animaciones CSS listas para usar.',moodboardTitle:'Mira el sistema completo.',moodboardSub:'Una composición viva creada con tu paleta, tipografía y tokens.',logoTitle:'Crea un mejor brief de logotipo.',logoSub:'Constructor local de prompts para generadores y diseñadores.',brandName:'Nombre de marca',style:'Estilo',outputModel:'Modelo de salida',buildPrompt:'Crear prompt',prompt:'Prompt generado',copy:'Copiar',brandbookTitle:'Tu manual de marca compacto.',brandbookSub:'Todo el sistema listo para exportar y construir.',copyCode:'Copiar código',copyJson:'Copiar JSON'},
    fr:{...i18n.en,navPalette:'Palette',navNaming:'Naming',navSlogan:'Slogan',navFonts:'Polices',navTokens:'Espacements et ombres',navAnimations:'Animations',navMoodboard:'Moodboard',navLogo:'Prompt de logo',navBrandbook:'Charte de marque',privateNote:'Privé par conception. Tout fonctionne dans votre navigateur.',save:'Enregistrer',step1:'ÉTAPE 01 — FONDATION',paletteTitle:'Transformez une émotion en couleur.',paletteSub:'Saisissez un mot ou extrayez les couleurs d’une image. La même entrée produit toujours le même système.',wordMode:'Mot vers couleur',photoMode:'Photo vers couleur',wordLabel:'Mot ou idée de marque',generate:'Générer le système',tryLabel:'Essayez :',uploadTitle:'Déposez une image ou choisissez un fichier',uploadSub:'PNG, JPG ou WEBP. Le fichier reste sur votre appareil.',generatedPalette:'Palette générée',regenerate:'Régénérer les couleurs libres',harmony:'Harmonie',history:'Palettes enregistrées',historySub:'Stockées uniquement dans ce navigateur.',clear:'Tout effacer',namingTitle:'Des noms à la bonne température.',namingSub:'Vingt idées déterministes issues de votre mot, ambiance et secteur.',refresh:'Actualiser',industry:'Secteur',sloganTitle:'Dites-le en une ligne.',sloganSub:'Des slogans construits par modèles pour votre direction de marque.',fontsTitle:'Une voix qui se voit.',fontsSub:'Des associations de polices système adaptées à l’ambiance.',tokensTitle:'Rythme, forme et profondeur.',tokensSub:'Des tokens d’interface adaptés à l’univers de votre marque.',copyCss:'Copier le CSS',spacing:'Échelle d’espacement',radius:'Échelle des rayons',shadows:'Ombres',animationsTitle:'Un mouvement avec du caractère.',animationsSub:'Prévisualisez et copiez des animations CSS prêtes à l’emploi.',moodboardTitle:'Voyez le système dans son ensemble.',moodboardSub:'Une composition vivante issue de votre palette, typographie et tokens.',logoTitle:'Créez un meilleur brief de logo.',logoSub:'Un générateur local de prompts pour outils visuels et designers.',brandName:'Nom de marque',style:'Style',outputModel:'Modèle de sortie',buildPrompt:'Créer le prompt',prompt:'Prompt généré',copy:'Copier',brandbookTitle:'Votre charte de marque compacte.',brandbookSub:'Tout le système prêt à exporter et à utiliser.',copyCode:'Copier le code',copyJson:'Copier le JSON'},
    de:{...i18n.en,navPalette:'Palette',navNaming:'Namensideen',navSlogan:'Slogan',navFonts:'Schriften',navTokens:'Abstände und Schatten',navAnimations:'Animationen',navMoodboard:'Moodboard',navLogo:'Logo-Prompt',navBrandbook:'Markenhandbuch',privateNote:'Privat konzipiert. Alles läuft in deinem Browser.',save:'Speichern',step1:'SCHRITT 01 — BASIS',paletteTitle:'Verwandle ein Gefühl in Farbe.',paletteSub:'Gib ein Wort ein oder extrahiere Farben aus einem Bild. Dieselbe Eingabe erzeugt immer dasselbe System.',wordMode:'Wort zu Farbe',photoMode:'Foto zu Farbe',wordLabel:'Markenwort oder Idee',generate:'System generieren',tryLabel:'Beispiele:',uploadTitle:'Bild ablegen oder Datei auswählen',uploadSub:'PNG, JPG oder WEBP. Die Datei bleibt auf deinem Gerät.',generatedPalette:'Generierte Palette',regenerate:'Freie Farben neu erzeugen',harmony:'Harmonie',history:'Gespeicherte Paletten',historySub:'Nur in diesem Browser gespeichert.',clear:'Alles löschen',namingTitle:'Namen mit der richtigen Temperatur.',namingSub:'Zwanzig deterministische Ideen aus Wort, Stimmung und Branche.',refresh:'Ideen erneuern',industry:'Branche',sloganTitle:'Sag es in einer Zeile.',sloganSub:'Vorlagenbasierte Slogans für deine Markenrichtung.',fontsTitle:'Eine Stimme, die man sehen kann.',fontsSub:'Systemschrift-Kombinationen passend zur aktuellen Stimmung.',tokensTitle:'Rhythmus, Form und Tiefe.',tokensSub:'Praktische Interface-Tokens für deine Markenstimmung.',copyCss:'CSS kopieren',spacing:'Abstandsskala',radius:'Radius-Skala',shadows:'Schatten',animationsTitle:'Bewegung mit Haltung.',animationsSub:'Produktionsreife CSS-Animationen ansehen und kopieren.',moodboardTitle:'Sieh das System als Ganzes.',moodboardSub:'Eine lebendige Komposition aus Palette, Typografie und Tokens.',logoTitle:'Erstelle ein besseres Logo-Briefing.',logoSub:'Lokaler Prompt-Builder für Bildgeneratoren und Designer.',brandName:'Markenname',style:'Stil',outputModel:'Ausgabemodell',buildPrompt:'Prompt erstellen',prompt:'Generierter Prompt',copy:'Kopieren',brandbookTitle:'Dein kompaktes Markenhandbuch.',brandbookSub:'Das gesamte System bereit für Export und Umsetzung.',copyCode:'Code kopieren',copyJson:'JSON kopieren'},
    it:{...i18n.en,navPalette:'Palette',navNaming:'Nomi',navSlogan:'Slogan',navFonts:'Font',navTokens:'Spaziature e ombre',navAnimations:'Animazioni',navMoodboard:'Moodboard',navLogo:'Prompt logo',navBrandbook:'Brand book',privateNote:'Privato per progettazione. Tutto funziona nel tuo browser.',save:'Salva',step1:'PASSO 01 — FONDAMENTA',paletteTitle:'Trasforma una sensazione in colore.',paletteSub:'Inserisci una parola o estrai i colori da un’immagine. Lo stesso input crea sempre lo stesso sistema.',wordMode:'Da parola a colore',photoMode:'Da foto a colore',wordLabel:'Parola o idea del brand',generate:'Genera sistema',tryLabel:'Prova:',uploadTitle:'Trascina un’immagine o scegli un file',uploadSub:'PNG, JPG o WEBP. Il file non lascia mai il tuo dispositivo.',generatedPalette:'Palette generata',regenerate:'Rigenera i colori sbloccati',harmony:'Armonia',history:'Palette salvate',historySub:'Memorizzate solo in questo browser.',clear:'Cancella tutto',namingTitle:'Nomi con la giusta temperatura.',namingSub:'Venti idee deterministiche basate su parola, atmosfera e settore.',refresh:'Aggiorna idee',industry:'Settore',sloganTitle:'Dillo in una riga.',sloganSub:'Slogan basati su modelli e adattati alla direzione del brand.',fontsTitle:'Una voce che puoi vedere.',fontsSub:'Abbinamenti di font di sistema scelti per l’atmosfera attuale.',tokensTitle:'Ritmo, forma e profondità.',tokensSub:'Token pratici per l’interfaccia, adattati al carattere del brand.',copyCss:'Copia CSS',spacing:'Scala spaziature',radius:'Scala raggi',shadows:'Ombre',animationsTitle:'Movimento con personalità.',animationsSub:'Visualizza e copia animazioni CSS pronte all’uso.',moodboardTitle:'Guarda il sistema nel suo insieme.',moodboardSub:'Una composizione dinamica creata con palette, font e token.',logoTitle:'Crea un brief migliore per il logo.',logoSub:'Un generatore locale di prompt per strumenti visivi e designer.',brandName:'Nome del brand',style:'Stile',outputModel:'Modello di output',buildPrompt:'Crea prompt',prompt:'Prompt generato',copy:'Copia',brandbookTitle:'Il tuo brand book compatto.',brandbookSub:'L’intero sistema pronto per essere esportato e utilizzato.',copyCode:'Copia codice',copyJson:'Copia JSON'},
    pt:{...i18n.en,navPalette:'Paleta',navNaming:'Nomes',navSlogan:'Slogan',navFonts:'Fontes',navTokens:'Espaçamentos e sombras',navAnimations:'Animações',navMoodboard:'Moodboard',navLogo:'Prompt de logotipo',navBrandbook:'Manual da marca',privateNote:'Privado por definição. Tudo funciona no seu navegador.',save:'Salvar',step1:'ETAPA 01 — BASE',paletteTitle:'Transforme uma sensação em cor.',paletteSub:'Digite uma palavra ou extraia cores de uma imagem. A mesma entrada sempre cria o mesmo sistema.',wordMode:'Palavra para cor',photoMode:'Foto para cor',wordLabel:'Palavra ou ideia da marca',generate:'Gerar sistema',tryLabel:'Experimente:',uploadTitle:'Arraste uma imagem ou escolha um arquivo',uploadSub:'PNG, JPG ou WEBP. O arquivo nunca sai do seu dispositivo.',generatedPalette:'Paleta gerada',regenerate:'Gerar novamente as cores livres',harmony:'Harmonia',history:'Paletas salvas',historySub:'Armazenadas somente neste navegador.',clear:'Limpar tudo',namingTitle:'Nomes com a temperatura certa.',namingSub:'Vinte ideias determinísticas criadas com sua palavra, clima e setor.',refresh:'Atualizar ideias',industry:'Setor',sloganTitle:'Diga em uma linha.',sloganSub:'Slogans baseados em modelos e adaptados à direção da marca.',fontsTitle:'Uma voz que você pode ver.',fontsSub:'Combinações de fontes do sistema escolhidas para o clima atual.',tokensTitle:'Ritmo, forma e profundidade.',tokensSub:'Tokens práticos de interface ajustados ao clima da marca.',copyCss:'Copiar CSS',spacing:'Escala de espaçamento',radius:'Escala de raios',shadows:'Sombras',animationsTitle:'Movimento com personalidade.',animationsSub:'Visualize e copie animações CSS prontas para uso.',moodboardTitle:'Veja o sistema completo.',moodboardSub:'Uma composição viva criada com sua paleta, tipografia e tokens.',logoTitle:'Crie um briefing de logotipo melhor.',logoSub:'Um construtor local de prompts para geradores e designers.',brandName:'Nome da marca',style:'Estilo',outputModel:'Modelo de saída',buildPrompt:'Criar prompt',prompt:'Prompt gerado',copy:'Copiar',brandbookTitle:'Seu manual de marca compacto.',brandbookSub:'Todo o sistema pronto para exportar e construir.',copyCode:'Copiar código',copyJson:'Copiar JSON'},
    zh:{...i18n.en,navPalette:'调色板',navNaming:'品牌命名',navSlogan:'标语',navFonts:'字体',navTokens:'间距与阴影',navAnimations:'动画',navMoodboard:'情绪板',navLogo:'标志提示词',navBrandbook:'品牌手册',privateNote:'隐私优先。所有操作均在浏览器中完成。',save:'保存',step1:'步骤 01 — 基础',paletteTitle:'将感受转化为色彩。',paletteSub:'输入一个词，或从图片中提取颜色。相同输入始终生成相同的系统。',wordMode:'文字生成颜色',photoMode:'图片提取颜色',wordLabel:'品牌词或创意',generate:'生成系统',tryLabel:'试试：',uploadTitle:'拖入图片或选择文件',uploadSub:'支持 PNG、JPG 或 WEBP。文件不会离开您的设备。',generatedPalette:'生成的调色板',regenerate:'重新生成未锁定颜色',harmony:'色彩和谐',history:'已保存的调色板',historySub:'仅保存在此浏览器中。',clear:'全部清除',namingTitle:'恰如其分的品牌名称。',namingSub:'根据关键词、氛围和行业确定性生成二十个创意。',refresh:'刷新创意',industry:'行业',sloganTitle:'用一句话表达。',sloganSub:'根据当前品牌方向，由本地模板生成标语。',fontsTitle:'看得见的品牌声音。',fontsSub:'根据当前氛围推荐浏览器安全字体组合。',tokensTitle:'节奏、形态与层次。',tokensSub:'根据品牌氛围调整的实用界面令牌。',copyCss:'复制 CSS',spacing:'间距比例',radius:'圆角比例',shadows:'阴影预设',animationsTitle:'有态度的动态效果。',animationsSub:'预览并复制可直接使用的 CSS 动画。',moodboardTitle:'完整呈现品牌系统。',moodboardSub:'由调色板、字体和设计令牌组成的动态视觉方案。',logoTitle:'创建更好的标志设计简报。',logoSub:'面向图像生成工具和设计师的本地提示词构建器。',brandName:'品牌名称',style:'风格',outputModel:'输出模型',buildPrompt:'生成提示词',prompt:'生成的提示词',copy:'复制',brandbookTitle:'您的精简品牌手册。',brandbookSub:'完整系统可随时导出并投入使用。',copyCode:'复制代码',copyJson:'复制 JSON'},
    ja:{...i18n.en,navPalette:'パレット',navNaming:'ネーミング',navSlogan:'スローガン',navFonts:'フォント',navTokens:'余白とシャドウ',navAnimations:'アニメーション',navMoodboard:'ムードボード',navLogo:'ロゴプロンプト',navBrandbook:'ブランドブック',privateNote:'プライバシーを重視。すべてブラウザ内で動作します。',save:'保存',step1:'ステップ 01 — 基盤',paletteTitle:'感覚を色に変える。',paletteSub:'言葉を入力するか、画像から色を抽出します。同じ入力からは常に同じシステムが生成されます。',wordMode:'言葉から色へ',photoMode:'写真から色へ',wordLabel:'ブランドの言葉やアイデア',generate:'システムを生成',tryLabel:'例：',uploadTitle:'画像をドロップまたはファイルを選択',uploadSub:'PNG、JPG、WEBPに対応。ファイルが端末外へ送信されることはありません。',generatedPalette:'生成されたパレット',regenerate:'未ロック色を再生成',harmony:'ハーモニー',history:'保存済みパレット',historySub:'このブラウザ内にのみ保存されます。',clear:'すべて削除',namingTitle:'ちょうどよい温度感の名前。',namingSub:'言葉、ムード、業界から20のアイデアを決定論的に生成します。',refresh:'アイデアを更新',industry:'業界',sloganTitle:'一行で伝える。',sloganSub:'現在のブランド方向に合わせてテンプレートからスローガンを作成します。',fontsTitle:'目に見える声。',fontsSub:'現在のムードに合うブラウザ標準フォントの組み合わせ。',tokensTitle:'リズム、形、奥行き。',tokensSub:'ブランドのムードに合わせた実用的なUIトークン。',copyCss:'CSSをコピー',spacing:'余白スケール',radius:'角丸スケール',shadows:'シャドウ',animationsTitle:'個性のある動き。',animationsSub:'すぐに使えるCSSアニメーションをプレビューしてコピーできます。',moodboardTitle:'システムをひとつに。',moodboardSub:'パレット、書体、トークンから生成されるビジュアル構成。',logoTitle:'より良いロゴブリーフを作る。',logoSub:'画像生成ツールやデザイナー向けのローカルプロンプトビルダー。',brandName:'ブランド名',style:'スタイル',outputModel:'出力モデル',buildPrompt:'プロンプトを作成',prompt:'生成されたプロンプト',copy:'コピー',brandbookTitle:'コンパクトなブランドブック。',brandbookSub:'システム全体をエクスポートしてすぐに活用できます。',copyCode:'コードをコピー',copyJson:'JSONをコピー'},
    ar:{...i18n.en,navPalette:'لوحة الألوان',navNaming:'الأسماء',navSlogan:'الشعار النصي',navFonts:'الخطوط',navTokens:'المسافات والظلال',navAnimations:'الحركة',navMoodboard:'لوحة الإلهام',navLogo:'موجّه الشعار',navBrandbook:'دليل العلامة',privateNote:'خصوصية كاملة. كل شيء يعمل داخل متصفحك.',save:'حفظ',step1:'الخطوة 01 — الأساس',paletteTitle:'حوّل الإحساس إلى لون.',paletteSub:'اكتب كلمة أو استخرج الألوان من صورة. الإدخال نفسه ينشئ النظام نفسه دائماً.',wordMode:'من كلمة إلى لون',photoMode:'من صورة إلى لون',wordLabel:'كلمة أو فكرة العلامة',generate:'إنشاء النظام',tryLabel:'جرّب:',uploadTitle:'اسحب صورة أو اختر ملفاً',uploadSub:'PNG أو JPG أو WEBP. لن يغادر الملف جهازك.',generatedPalette:'لوحة الألوان المنشأة',regenerate:'إعادة إنشاء الألوان غير المقفلة',harmony:'التناغم',history:'اللوحات المحفوظة',historySub:'محفوظة في هذا المتصفح فقط.',clear:'مسح الكل',namingTitle:'أسماء بالإحساس المناسب.',namingSub:'عشرون فكرة حتمية مبنية على كلمتك والمزاج والمجال.',refresh:'تحديث الأفكار',industry:'المجال',sloganTitle:'قلها في سطر واحد.',sloganSub:'شعارات نصية مبنية على قوالب لاتجاه علامتك.',fontsTitle:'صوت يمكنك رؤيته.',fontsSub:'توليفات خطوط آمنة للمتصفح تناسب المزاج الحالي.',tokensTitle:'إيقاع وشكل وعمق.',tokensSub:'رموز تصميم عملية مضبوطة حسب مزاج العلامة.',copyCss:'نسخ CSS',spacing:'مقياس المسافات',radius:'مقياس الزوايا',shadows:'الظلال',animationsTitle:'حركة ذات شخصية.',animationsSub:'عاين وانسخ حركات CSS جاهزة للاستخدام.',moodboardTitle:'شاهد النظام كاملاً.',moodboardSub:'تكوين حي من لوحة الألوان والخطوط ورموز التصميم.',logoTitle:'أنشئ وصفاً أفضل للشعار.',logoSub:'منشئ محلي للموجّهات خاص بالمولدات والمصممين.',brandName:'اسم العلامة',style:'الأسلوب',outputModel:'نموذج الإخراج',buildPrompt:'إنشاء الموجّه',prompt:'الموجّه المنشأ',copy:'نسخ',brandbookTitle:'دليل علامتك المختصر.',brandbookSub:'النظام بالكامل جاهز للتصدير والبناء.',copyCode:'نسخ الرمز',copyJson:'نسخ JSON'}
  });
  const uiMessages={
    copied:{en:'Copied',ru:'Скопировано',es:'Copiado',fr:'Copié',de:'Kopiert',it:'Copiato',pt:'Copiado',zh:'已复制',ja:'コピーしました',ar:'تم النسخ'},
    saved:{en:'Palette saved',ru:'Палитра сохранена',es:'Paleta guardada',fr:'Palette enregistrée',de:'Palette gespeichert',it:'Palette salvata',pt:'Paleta salva',zh:'调色板已保存',ja:'パレットを保存しました',ar:'تم حفظ لوحة الألوان'},
    empty:{en:'No saved palettes yet.',ru:'Сохранённых палитр пока нет.',es:'Aún no hay paletas guardadas.',fr:'Aucune palette enregistrée.',de:'Noch keine Paletten gespeichert.',it:'Nessuna palette salvata.',pt:'Nenhuma paleta salva ainda.',zh:'尚无已保存的调色板。',ja:'保存済みのパレットはありません。',ar:'لا توجد لوحات محفوظة بعد.'},
    extracted:{en:'Colors extracted locally',ru:'Цвета извлечены локально',es:'Colores extraídos localmente',fr:'Couleurs extraites localement',de:'Farben lokal extrahiert',it:'Colori estratti localmente',pt:'Cores extraídas localmente',zh:'已在本地提取颜色',ja:'端末内で色を抽出しました',ar:'تم استخراج الألوان محلياً'},
    rebuilt:{en:'Prompt rebuilt',ru:'Промпт обновлён',es:'Prompt actualizado',fr:'Prompt actualisé',de:'Prompt aktualisiert',it:'Prompt aggiornato',pt:'Prompt atualizado',zh:'提示词已更新',ja:'プロンプトを更新しました',ar:'تم تحديث الموجّه'}
  };
  const message=key=>uiMessages[key]?.[state.language]||uiMessages[key]?.en||'';
  Object.assign(i18n, {
    en:{navPalette:'Palette',navNaming:'Naming',navSlogan:'Slogan',navFonts:'Fonts',navTokens:'Spacing & Shadows',navAnimations:'Animations',navMoodboard:'Moodboard',navLogo:'Logo Prompt',navBrandbook:'Brandbook',privateNote:'Private by design. Everything runs in your browser.',save:'Save',step1:'STEP 01 — FOUNDATION',paletteTitle:'Turn a feeling into color.',paletteSub:'Enter a word or extract colors from an image. The same input always creates the same system.',wordMode:'Word to color',photoMode:'Photo to color',wordLabel:'Brand word or idea',generate:'Generate system',tryLabel:'Try:',uploadTitle:'Drop an image or choose a file',uploadSub:'PNG, JPG or WEBP. It never leaves your device.',generatedPalette:'Generated palette',regenerate:'Regenerate unlocked',png:'PNG',harmony:'Harmony',history:'Saved palettes',historySub:'Stored only in this browser.',clear:'Clear all',namingTitle:'Names with the right temperature.',namingSub:'Twenty deterministic ideas built from your word, mood and industry.',refresh:'Refresh ideas',industry:'Industry',sloganTitle:'Say it in one line.',sloganSub:'Template-built slogans shaped by your current brand direction.',fontsTitle:'A voice you can see.',fontsSub:'Browser-safe font pairings selected for the current mood.',tokensTitle:'Rhythm, shape and depth.',tokensSub:'Practical interface tokens tuned to your brand mood.',copyCss:'Copy CSS',spacing:'Spacing scale',radius:'Radius scale',shadows:'Shadow presets',animationsTitle:'Motion with a point of view.',animationsSub:'Preview and copy production-ready CSS animation presets.',moodboardTitle:'See the system together.',moodboardSub:'A living composition generated from your palette, type and tokens.',logoTitle:'Build a better logo brief.',logoSub:'A local template builder for image-generation tools and designers.',brandName:'Brand name',style:'Style',outputModel:'Output model',buildPrompt:'Build prompt',prompt:'Generated prompt',copy:'Copy',brandbookTitle:'Your compact brandbook.',brandbookSub:'Everything generated here, ready to export and build with.',copyCode:'Copy code',copyJson:'Copy JSON'},
    ru:{navPalette:'Палитра',navNaming:'Нейминг',navSlogan:'Слоган',navFonts:'Шрифты',navTokens:'Отступы и тени',navAnimations:'Анимации',navMoodboard:'Мудборд',navLogo:'Промпт логотипа',navBrandbook:'Брендбук',privateNote:'Полная приватность. Всё работает в вашем браузере.',save:'Сохранить',step1:'ШАГ 01 — ОСНОВА',paletteTitle:'Превратите ощущение в цвет.',paletteSub:'Введите слово или извлеките цвета из изображения. Одинаковый ввод всегда создаёт одинаковую систему.',wordMode:'Слово в цвет',photoMode:'Фото в цвет',wordLabel:'Слово или идея бренда',generate:'Создать систему',tryLabel:'Например:',uploadTitle:'Перетащите изображение или выберите файл',uploadSub:'PNG, JPG или WEBP. Файл не покинет устройство.',generatedPalette:'Созданная палитра',regenerate:'Обновить открытые',png:'PNG',harmony:'Гармония',history:'Сохранённые палитры',historySub:'Хранятся только в этом браузере.',clear:'Удалить всё',namingTitle:'Названия нужной температуры.',namingSub:'Двадцать идей на основе вашего слова, настроения и сферы.',refresh:'Обновить идеи',industry:'Сфера',sloganTitle:'Скажите это одной строкой.',sloganSub:'Шаблонные слоганы в направлении вашего бренда.',fontsTitle:'Голос, который можно увидеть.',fontsSub:'Системные пары шрифтов для текущего настроения.',tokensTitle:'Ритм, форма и глубина.',tokensSub:'Практичные токены интерфейса в настроении бренда.',copyCss:'Копировать CSS',spacing:'Шкала отступов',radius:'Скругления',shadows:'Наборы теней',animationsTitle:'Движение с характером.',animationsSub:'Просматривайте и копируйте готовые CSS-анимации.',moodboardTitle:'Увидьте систему целиком.',moodboardSub:'Живая композиция из палитры, шрифтов и токенов.',logoTitle:'Создайте точный бриф логотипа.',logoSub:'Локальный конструктор промптов для генераторов и дизайнеров.',brandName:'Название бренда',style:'Стиль',outputModel:'Модель',buildPrompt:'Создать промпт',prompt:'Готовый промпт',copy:'Копировать',brandbookTitle:'Ваш компактный брендбук.',brandbookSub:'Вся система готова к экспорту и разработке.',copyCode:'Копировать код',copyJson:'Копировать JSON'}
  });
  for(const code of ['es','fr','de','it','pt','zh','ja','ar']) i18n[code]={...i18n.en,...i18n[code]};
  const footerI18n={
    en:['A local brand system generator for words, images and ideas.','Everything stays on your device. No uploads, accounts or API keys.'],
    ru:['Локальный генератор бренд-систем из слов, изображений и идей.','Всё остаётся на вашем устройстве. Без загрузок, аккаунтов и API-ключей.'],
    es:['Un generador local de sistemas de marca para palabras, imágenes e ideas.','Todo permanece en tu dispositivo. Sin cargas, cuentas ni claves API.'],
    fr:['Un générateur local de systèmes de marque pour les mots, images et idées.','Tout reste sur votre appareil. Aucun envoi, compte ou clé API.'],
    de:['Ein lokaler Markensystem-Generator für Wörter, Bilder und Ideen.','Alles bleibt auf deinem Gerät. Keine Uploads, Konten oder API-Schlüssel.'],
    it:['Un generatore locale di sistemi di marca per parole, immagini e idee.','Tutto resta sul tuo dispositivo. Nessun upload, account o chiave API.'],
    pt:['Um gerador local de sistemas de marca para palavras, imagens e ideias.','Tudo permanece no seu dispositivo. Sem uploads, contas ou chaves de API.'],
    zh:['为文字、图像和创意打造的本地品牌系统生成器。','所有内容均保留在您的设备上，无需上传、账户或 API 密钥。'],
    ja:['言葉、画像、アイデアのためのローカルブランドシステム生成ツール。','すべて端末内に保存されます。アップロード、アカウント、APIキーは不要です。'],
    ar:['مولّد محلي لأنظمة العلامات التجارية من الكلمات والصور والأفكار.','يبقى كل شيء على جهازك. بلا رفع ملفات أو حسابات أو مفاتيح API.']
  };
  for(const [code,[footerTagline,footerPrivacy]] of Object.entries(footerI18n)) Object.assign(i18n[code],{footerTagline,footerPrivacy});

  const initial = {word:'Stillness',seed:0,mood:moods[1],harmony:'analogous',colors:[],locked:Array(6).fill(false),industry:'creative',names:[],slogans:[],fontPair:null,tokens:null,language:store.get('wps-language','en'),theme:store.get('wps-theme','light')};
  let state = initial;
  let toastTimer;
  function hash(str){let h=2166136261;for(const ch of str.toLowerCase().trim()){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
  function hslToRgb(h,s,l){s/=100;l/=100;const c=(1-Math.abs(2*l-1))*s,x=c*(1-Math.abs((h/60)%2-1)),m=l-c/2;let r=0,g=0,b=0;if(h<60)[r,g,b]=[c,x,0];else if(h<120)[r,g,b]=[x,c,0];else if(h<180)[r,g,b]=[0,c,x];else if(h<240)[r,g,b]=[0,x,c];else if(h<300)[r,g,b]=[x,0,c];else[r,g,b]=[c,0,x];return [r,g,b].map(v=>Math.round((v+m)*255))}
  function rgbToHsl(r,g,b){r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;let h=0;if(d){if(max===r)h=60*(((g-b)/d)%6);else if(max===g)h=60*((b-r)/d+2);else h=60*((r-g)/d+4)}if(h<0)h+=360;const l=(max+min)/2,s=d?d/(1-Math.abs(2*l-1)):0;return [Math.round(h),Math.round(s*100),Math.round(l*100)]}
  function rgbToHex([r,g,b]){return '#'+[r,g,b].map(v=>v.toString(16).padStart(2,'0')).join('').toUpperCase()}
  function hexRgb(hex){return [1,3,5].map(i=>parseInt(hex.slice(i,i+2),16))}
  function makePalette(seed, mood, harmony, variation=0){const offs=harmonyOffsets[harmony],base=(mood.hue+(seed%71)-35+variation*13+360)%360;return offs.map((off,i)=>{let sat=clamp(mood.sat+((seed>>(i*3))%19)-9,4,96);let light=mood.minL+(i/(offs.length-1))*(mood.maxL-mood.minL);if(harmony==='monochrome')sat=Math.min(sat,18);if(harmony==='neutral accent'&&i!==3)sat=Math.min(sat,12);light=clamp(light+(((seed>>(i+2))%9)-4),5,96);const h=(base+off+360)%360,rgb=hslToRgb(h,sat,light);return{h:Math.round(h),s:Math.round(sat),l:Math.round(light),rgb,hex:rgbToHex(rgb)}})}
  function createSystem(word, variation=0){word=(word||'Untitled').trim();const seed=hash(word)+variation*7919,mood=moods[seed%moods.length];state.word=word;state.seed=seed;state.mood=mood;state.harmony=variation?state.harmony:mood.harmony;const fresh=makePalette(seed,mood,state.harmony,variation);state.colors=fresh.map((c,i)=>state.locked[i]&&state.colors[i]?state.colors[i]:c);state.names=generateNames();state.slogans=generateSlogans();state.fontPair=fontPairs()[seed%fontPairs().length];state.tokens=generateTokens();$('#wordInput').value=word;$('#brandNameInput').value=word;renderAll()}
  function contrast(hex){const [r,g,b]=hexRgb(hex).map(v=>v/255);const y=.299*r+.587*g+.114*b;return y>.58?'#151613':'#ffffff'}
  function renderPalette(){
    $('#moodPill').textContent=state.mood.label.toUpperCase();$('#paletteName').textContent=`${state.word} / ${state.mood.label}`;
    $('#swatchGrid').innerHTML=state.colors.map((c,i)=>`<article class="swatch" style="background:${c.hex};color:${contrast(c.hex)}"><div class="swatch-actions"><button data-lock="${i}" title="Lock">${state.locked[i]?'●':'○'}</button></div><div class="swatch-info"><strong data-copy="${c.hex}">${c.hex}</strong><small>RGB ${c.rgb.join(' · ')}</small><small>HSL ${c.h} · ${c.s} · ${c.l}</small></div></article>`).join('');
    $('#harmonyButtons').innerHTML=harmonyLabels.map(h=>`<button class="${state.harmony===h?'active':''}" data-harmony="${h}">${h}</button>`).join('');
  }
  const prefixes=['Lu','Nova','Vera','Aero','Mono','Alta','Evo','Nexa','Sola','Chrom','Forma','Ori'];
  const roots=['lum','chrom','palett','hue','brand','mora','vela','nori','aura','lith','sora','mira','kind','flux','echo'];
  const endings=['a','io','iq','ora','ly','um','is','eo','en','ica','ive','on'];
  const industryWords={creative:['form','maker','canvas','craft'],technology:['byte','grid','logic','node'],fashion:['mode','thread','atelier','wear'],wellness:['vita','calm','well','bloom'],finance:['ledger','mint','capital','fund'],food:['table','grain','feast','taste']};
  function cap(s){return s.charAt(0).toUpperCase()+s.slice(1)}
  function generateNames(offset=0){const seed=state.seed+offset*97,word=state.word.replace(/[^a-zа-яё]/gi,'').slice(0,5).toLowerCase()||'nova',iw=industryWords[state.industry]||industryWords.creative;const out=[];for(let i=0;i<20;i++){let n;switch(i%5){case 0:n=pick(prefixes,seed,i)+pick(endings,seed,i*3);break;case 1:n=word+pick(endings,seed,i);break;case 2:n=pick(roots,seed,i)+pick(endings,seed,i*7);break;case 3:n=pick(iw,seed,i)+pick(endings,seed,i*5);break;default:n=pick(prefixes,seed,i)+pick(roots,seed,i*2)}out.push(cap(n).replace(/(.)\1{2,}/g,'$1$1'))}return [...new Set(out)].slice(0,20)}
  const sloganTemplates=[
    w=>`${cap(w)} begins with a feeling.`,w=>`Turn ${w} into a visual language.`,w=>`A clearer way to feel ${w}.`,w=>`Built for ideas in motion.`,w=>`Color with a point of view.`,w=>`Make the essential visible.`,w=>`From one word, a whole world.`,w=>`${cap(w)}, made tangible.`,w=>`Designed to feel exactly right.`,w=>`Find the signal in the noise.`,w=>`Form follows feeling.`,w=>`The new shape of ${w}.`,w=>`Quiet ideas. Lasting impact.`,w=>`Identity, distilled.`,w=>`See what ${w} can become.`
  ];
  function generateSlogans(offset=0){return Array.from({length:10},(_,i)=>pick(sloganTemplates,state.seed+offset*43,i*7)(state.word.toLowerCase()))}
  function fontPairs(){return[
    {type:'Editorial',head:'Georgia',body:'Arial',headCss:'Georgia, serif',bodyCss:'Arial, sans-serif',reason:'Classic contrast with calm readability.'},
    {type:'Tech',head:'Arial Black',body:'Segoe UI',headCss:'"Arial Black", sans-serif',bodyCss:'"Segoe UI", sans-serif',reason:'Strong geometry paired with a neutral interface voice.'},
    {type:'Luxury',head:'Times New Roman',body:'Helvetica',headCss:'"Times New Roman", serif',bodyCss:'Helvetica, Arial, sans-serif',reason:'High-contrast elegance supported by crisp utility.'},
    {type:'Playful',head:'Trebuchet MS',body:'Verdana',headCss:'"Trebuchet MS", sans-serif',bodyCss:'Verdana, sans-serif',reason:'Friendly shapes with excellent screen legibility.'},
    {type:'Minimal',head:'Helvetica Neue',body:'Arial',headCss:'"Helvetica Neue", Helvetica, sans-serif',bodyCss:'Arial, sans-serif',reason:'Quiet, adaptable and deliberately familiar.'},
    {type:'Brutalist',head:'Impact',body:'Courier New',headCss:'Impact, sans-serif',bodyCss:'"Courier New", monospace',reason:'Unapologetic display type with technical texture.'}
  ]}
  function generateTokens(){const id=state.mood.id;let unit=8,radius=10,space=1;if(id==='brutal'){radius=0;unit=7}else if(id==='luxury'){unit=10;space=1.25;radius=4}else if(['playful','pastel'].includes(id))radius=18;else if(id==='cyber'){unit=6;radius=4}else if(id==='minimal')radius=6;const spacing=[.5,1,1.5,2,3,4,6].map(v=>Math.round(v*unit*space));return{spacing,radius:[0,Math.round(radius/2),radius,radius*2,999],shadows:id==='brutal'?['4px 4px 0 rgba(0,0,0,.9)','8px 8px 0 rgba(0,0,0,.75)','12px 12px 0 rgba(0,0,0,.6)']:['0 2px 8px rgba(0,0,0,.08)','0 10px 30px rgba(0,0,0,.12)','0 24px 60px rgba(0,0,0,.18)'],container:id==='luxury'?1280:1120,cardPadding:unit*3,buttonHeight:unit*5}}
  function renderNames(){$('#namesGrid').innerHTML=state.names.map(n=>`<div class="idea-card"><b>${n}</b><button data-copy="${n}">Copy</button></div>`).join('')}
  function renderSlogans(){$('#sloganList').innerHTML=state.slogans.map((s,i)=>`<div class="list-item"><span><small>0${i+1}</small> <strong>${s}</strong></span><button data-copy="${s}">Copy</button></div>`).join('')}
  function renderFonts(){const pairs=fontPairs(),ordered=[state.fontPair,...pairs.filter(p=>p!==state.fontPair)];$('#fontGrid').innerHTML=ordered.map((p,i)=>`<article class="font-card"><small>${i===0?'RECOMMENDED · ':''}${p.type}</small><div class="font-preview" style="font-family:${p.headCss}">${state.word}<br><span style="font-family:${p.bodyCss};font-size:.42em">A visual system from a single word.</span></div><p>${p.reason}</p><div class="font-meta"><span>${p.head} + ${p.body}</span><button class="text-button" data-copy="font-family: ${p.headCss};">Copy CSS</button></div></article>`).join('')}
  function renderTokens(){const t=state.tokens;$('#spacingScale').innerHTML=t.spacing.map((v,i)=>`<div class="scale-row"><span>space-${i+1}</span><i style="width:${Math.min(v*3,240)}px"></i><b>${v}px</b></div>`).join('');$('#radiusScale').innerHTML=`<div class="radius-row">${t.radius.slice(0,4).map((v,i)=>`<div class="radius-demo" style="border-radius:${v}px">${v}px</div>`).join('')}</div>`;$('#shadowGrid').innerHTML=t.shadows.map((v,i)=>`<div class="shadow-demo" style="box-shadow:${v}">Shadow ${i+1}</div>`).join('')}
  const animations=[['Fade in','fadeIn','.element { animation: fadeIn .5s ease both; }'],['Slide up','slideUp','.element { animation: slideUp .6s cubic-bezier(.2,.8,.2,1) both; }'],['Soft scale','softScale','.element { animation: softScale 1.8s ease-in-out infinite; }'],['Brutal snap','brutalSnap','.element { animation: brutalSnap .7s steps(2) infinite; }'],['Slow float','slowFloat','.element { animation: slowFloat 3s ease-in-out infinite; }'],['Hover lift','hoverLift','.element { animation: hoverLift 1.5s ease-in-out infinite; }'],['Pulse glow','pulseGlow','.element { animation: pulseGlow 2s ease-in-out infinite; }']];
  function renderAnimations(){$('#animationGrid').innerHTML=animations.map(([name,key,css])=>`<article class="animation-card"><div class="motion-stage"><i class="motion-shape" style="animation:${key} 1.8s ease-in-out infinite"></i></div><footer><b>${name}</b><button data-copy="${css}">Copy CSS</button></footer></article>`).join('')}
  function renderMoodboard(){const c=state.colors,p=state.fontPair;$('#moodboard').innerHTML=`<div class="mood-panel mood-hero" style="background:${c[0].hex};color:${contrast(c[0].hex)}"><span>${state.mood.label} / ${state.mood.description}</span><h2 style="font-family:${p.headCss}">${state.word}</h2><small>${state.slogans[0]}</small></div><div class="mood-panel mood-type" style="background:${c[4].hex};color:${contrast(c[4].hex)}"><b style="font:32px ${p.headCss}">Aa</b><div class="mood-card-demo"><b>${state.names[0]}</b><p>${state.slogans[2]}</p><button class="primary">Discover</button></div></div><div class="mood-panel pattern" style="background-color:${c[2].hex};background-image:linear-gradient(45deg,${c[3].hex} 25%,transparent 25%,transparent 75%,${c[3].hex} 75%)"></div>`}
  function buildPrompt(){const name=$('#brandNameInput').value.trim()||state.word,style=$('#logoStyle').value,model=$('#outputModel').value,shape=pick(['circle','interlocking lines','abstract monogram','modular grid','single continuous form','negative-space symbol'],state.seed);const hex=state.colors.map(c=>c.hex).join(', ');const lead=model==='Midjourney'?'/imagine prompt: ':model==='DALL-E'?'Create an image of: ':'';const prompt=`${lead}${style} logo for ${name}, inspired by a ${state.mood.label.toLowerCase()} mood. Create a ${state.mood.logo} based on ${shape}. Palette: ${hex}. Typography direction: ${state.mood.font}. Flat vector construction, balanced negative space, strong silhouette, scalable from favicon to signage. Present on a plain ${state.colors[5].hex} background. Usage: primary brand identity and digital product.`;const negative='No 3D, no photorealism, no mockup, no gradients, no stock symbols, no watermark, no decorative background, no extra text unless requested.';$('#promptOutput').textContent=prompt;$('#negativeOutput').textContent=negative;return{prompt,negative}}
  function cssVariables(){return`:root {\n${state.colors.map((c,i)=>`  --color-${i+1}: ${c.hex};`).join('\n')}\n${state.tokens.spacing.map((v,i)=>`  --space-${i+1}: ${v}px;`).join('\n')}\n  --radius-card: ${state.tokens.radius[2]}px;\n  --shadow-card: ${state.tokens.shadows[1]};\n}`}
  function tailwindTokens(){return`colors: {\n${state.colors.map((c,i)=>`  brand${i+1}: '${c.hex}',`).join('\n')}\n},\nspacing: { ${state.tokens.spacing.map((v,i)=>`'${i+1}': '${v}px'`).join(', ')} },\nborderRadius: { brand: '${state.tokens.radius[2]}px' }`}
  function figmaTokens(){return JSON.stringify({color:Object.fromEntries(state.colors.map((c,i)=>[`brand-${i+1}`,{$type:'color',$value:c.hex}])),spacing:Object.fromEntries(state.tokens.spacing.map((v,i)=>[`${i+1}`,{$type:'dimension',$value:`${v}px`}]))},null,2)}
  function brandData(){const prompts=buildPrompt();return{app:'WordPalette App',word:state.word,mood:state.mood,palette:state.colors,typography:state.fontPair,slogan:state.slogans[0],namingIdeas:state.names.slice(0,10),logoPrompt:prompts,tokens:state.tokens,generatedAt:new Date().toISOString()}}
  function renderBrandbook(){const c=state.colors,p=state.fontPair;$('#brandbook').innerHTML=`<div class="book-hero" style="background:${c[0].hex};color:${contrast(c[0].hex)}"><small>${state.mood.label.toUpperCase()} — BRAND SYSTEM</small><h2 style="font-family:${p.headCss}">${state.word}</h2><p>${state.slogans[0]}</p></div><div class="book-grid"><div class="book-section"><h3>01 — Palette</h3><div class="book-colors">${c.map(x=>`<i title="${x.hex}" style="background:${x.hex}"></i>`).join('')}</div></div><div class="book-section"><h3>02 — Typography</h3><p style="font:34px ${p.headCss}">${p.head}</p><p style="font-family:${p.bodyCss}">${p.body} for clear supporting text.</p></div><div class="book-section"><h3>03 — Voice</h3><p>${state.slogans.slice(0,3).join('<br><br>')}</p></div><div class="book-section"><h3>04 — Naming territory</h3><p>${state.names.slice(0,8).join(' · ')}</p></div></div>`}
  function renderAll(){renderPalette();renderNames();renderSlogans();renderFonts();renderTokens();renderAnimations();renderMoodboard();buildPrompt();renderBrandbook();applyLanguage()}
  function toast(msg){clearTimeout(toastTimer);$('#toast').textContent=msg;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),1800)}
  async function copy(text){try{await navigator.clipboard.writeText(text)}catch{const t=document.createElement('textarea');t.value=text;document.body.append(t);t.select();document.execCommand('copy');t.remove()}toast(message('copied'))}
  function applyLanguage(){const pack=i18n[state.language]||i18n.en;document.documentElement.lang=state.language;document.documentElement.dir=state.language==='ar'?'rtl':'ltr';$$('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(pack[key])el.textContent=pack[key]});$('#languageSelect').value=state.language;const active=$('.nav-item.active i');if(active)$('#sectionTitle').textContent=active.textContent}
  function setTheme(theme){state.theme=theme;document.documentElement.dataset.theme=theme;store.set('wps-theme',theme)}
  function savePalette(){const list=store.get('wps-history',[]);list.unshift({id:Date.now(),word:state.word,mood:state.mood.id,colors:state.colors});store.set('wps-history',list.slice(0,12));renderHistory();toast(message('saved'))}
  function renderHistory(){const list=store.get('wps-history',[]);$('#historyList').innerHTML=list.length?list.map(x=>`<div class="history-item" data-history="${x.id}"><div class="mini-palette">${x.colors.map(c=>`<i style="background:${c.hex}"></i>`).join('')}</div><b>${x.word} / ${x.mood}</b><button data-delete-history="${x.id}">×</button></div>`).join(''):`<div class="empty">${message('empty')}</div>`}
  function download(content,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
  function palettePng(title=state.word,brandbook=false){const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d'),W=brandbook?1600:1200,H=brandbook?1000:700;canvas.width=W;canvas.height=H;ctx.fillStyle=state.colors[5].hex;ctx.fillRect(0,0,W,H);ctx.fillStyle=contrast(state.colors[5].hex);ctx.font=`${brandbook?'92':'64'}px Georgia`;ctx.fillText(title,70,110);ctx.font='24px Arial';ctx.fillText(`${state.mood.label} — ${state.slogans[0]}`,70,158);const y=brandbook?260:220,w=(W-140)/state.colors.length;state.colors.forEach((c,i)=>{ctx.fillStyle=c.hex;ctx.fillRect(70+i*w,y,w,brandbook?420:350);ctx.fillStyle=contrast(c.hex);ctx.font='18px monospace';ctx.fillText(c.hex,82+i*w,y+(brandbook?390:320))});if(brandbook){ctx.fillStyle=contrast(state.colors[5].hex);ctx.font='28px Georgia';ctx.fillText(`Typography: ${state.fontPair.head} + ${state.fontPair.body}`,70,760);ctx.font='22px Arial';ctx.fillText(`Names: ${state.names.slice(0,6).join(' · ')}`,70,820);ctx.fillText('Generated locally with WordPalette App',70,930)}canvas.toBlob(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${state.word.toLowerCase().replace(/\s+/g,'-')}-${brandbook?'brandbook':'palette'}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)},'image/png')}
  async function extractPhoto(file){const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const canvas=$('#photoCanvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.clearRect(0,0,200,200);const scale=Math.max(200/img.width,200/img.height),w=img.width*scale,h=img.height*scale;ctx.drawImage(img,(200-w)/2,(200-h)/2,w,h);const data=ctx.getImageData(0,0,200,200).data,pts=[];for(let i=0;i<data.length;i+=40){if(data[i+3]>180)pts.push([data[i],data[i+1],data[i+2]])}const colors=kmeans(pts,6,hash(file.name));state.word=file.name.replace(/\.[^.]+$/,'');state.seed=hash(state.word);state.mood=moods[state.seed%moods.length];state.colors=colors.map(rgb=>{const [h,s,l]=rgbToHsl(...rgb);return{rgb,h,s,l,hex:rgbToHex(rgb)}});state.locked=Array(6).fill(false);state.names=generateNames();state.slogans=generateSlogans();state.fontPair=fontPairs()[state.seed%6];state.tokens=generateTokens();$('#wordInput').value=state.word;$('#brandNameInput').value=state.word;renderAll();URL.revokeObjectURL(url);toast(message('extracted'))};img.src=url}
  function kmeans(points,k,seed){let centers=Array.from({length:k},(_,i)=>[...points[(seed+i*997)%points.length]]);for(let iter=0;iter<12;iter++){const groups=Array.from({length:k},()=>[]);for(const p of points){let bi=0,bd=Infinity;centers.forEach((c,i)=>{const d=(p[0]-c[0])**2+(p[1]-c[1])**2+(p[2]-c[2])**2;if(d<bd){bd=d;bi=i}});groups[bi].push(p)}centers=centers.map((c,i)=>groups[i].length?c.map((_,j)=>Math.round(groups[i].reduce((a,p)=>a+p[j],0)/groups[i].length)):c)}return centers.sort((a,b)=>rgbToHsl(...a)[2]-rgbToHsl(...b)[2])}

  // Navigation and interactions
  function activateSection(section){const btn=$(`.nav-item[data-section="${section}"]`);if(!btn)return;$$('.nav-item').forEach(x=>x.classList.toggle('active',x===btn));$$('.view').forEach(v=>v.classList.toggle('active',v.id===`${section}-view`));$('#sectionTitle').textContent=$('i',btn).textContent;$('#sidebar').classList.remove('open');window.scrollTo(0,0);history.replaceState(null,'',`#${section}`)}
  $$('.nav-item').forEach(btn=>btn.onclick=()=>activateSection(btn.dataset.section));
  window.addEventListener('hashchange',()=>activateSection(location.hash.slice(1)));
  $('#menuButton').onclick=()=>$('#sidebar').classList.toggle('open');
  $$('.mode-tabs button').forEach(b=>b.onclick=()=>{$$('.mode-tabs button').forEach(x=>x.classList.toggle('active',x===b));$('#wordPanel').classList.toggle('hidden',b.dataset.mode!=='word');$('#photoPanel').classList.toggle('hidden',b.dataset.mode!=='photo')});
  $('#generateButton').onclick=()=>{state.locked=Array(6).fill(false);createSystem($('#wordInput').value)};$('#wordInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('#generateButton').click()});$$('.suggestions button').forEach(b=>b.onclick=()=>createSystem(b.textContent));
  let variation=0;$('#regenerateButton').onclick=()=>createSystem(state.word,++variation);$('#saveButton').onclick=savePalette;
  $('#swatchGrid').addEventListener('click',e=>{const lock=e.target.closest('[data-lock]');if(lock){const i=+lock.dataset.lock;state.locked[i]=!state.locked[i];renderPalette();return}const c=e.target.closest('[data-copy]');if(c)copy(c.dataset.copy)});
  $('#harmonyButtons').addEventListener('click',e=>{const b=e.target.closest('[data-harmony]');if(!b)return;state.harmony=b.dataset.harmony;state.colors=makePalette(state.seed,state.mood,state.harmony,variation);renderAll()});
  $('#photoInput').onchange=e=>{if(e.target.files[0])extractPhoto(e.target.files[0])};
  $('#clearHistory').onclick=()=>{store.set('wps-history',[]);renderHistory()};$('#historyList').addEventListener('click',e=>{const d=e.target.closest('[data-delete-history]');if(d){store.set('wps-history',store.get('wps-history',[]).filter(x=>x.id!==+d.dataset.deleteHistory));renderHistory();e.stopPropagation();return}const item=e.target.closest('[data-history]');if(item){const x=store.get('wps-history',[]).find(y=>y.id===+item.dataset.history);state.word=x.word;state.mood=moods.find(m=>m.id===x.mood)||moods[0];state.seed=hash(x.word);state.colors=x.colors;state.names=generateNames();state.slogans=generateSlogans();state.fontPair=fontPairs()[state.seed%6];state.tokens=generateTokens();renderAll()}});
  $('#languageSelect').onchange=e=>{state.language=e.target.value;store.set('wps-language',state.language);applyLanguage();renderHistory()};$('#themeButton').onclick=()=>setTheme(state.theme==='light'?'dark':'light');
  let nameOffset=0,sloganOffset=0;$('[data-action="refresh-names"]').onclick=()=>{state.names=generateNames(++nameOffset);renderNames();renderMoodboard();renderBrandbook()};$('[data-action="refresh-slogans"]').onclick=()=>{state.slogans=generateSlogans(++sloganOffset);renderSlogans();renderMoodboard();renderBrandbook()};$('#industrySelect').onchange=e=>{state.industry=e.target.value;state.names=generateNames(++nameOffset);state.slogans=generateSlogans(++sloganOffset);renderNames();renderSlogans()};
  document.addEventListener('click',e=>{const c=e.target.closest('[data-copy]');if(c&&!c.closest('#swatchGrid'))copy(c.dataset.copy)});$('#copyCssButton').onclick=()=>copy(cssVariables());$('#buildPrompt').onclick=()=>{buildPrompt();toast(message('rebuilt'))};$('#copyPrompt').onclick=()=>copy(`${$('#promptOutput').textContent}\n\nNegative prompt: ${$('#negativeOutput').textContent}`);
  $('#exportPalettePng').onclick=()=>palettePng();$('#exportMoodboard').onclick=()=>palettePng(`${state.word} Moodboard`);$('#exportBrandbookPng').onclick=()=>palettePng(state.word,true);$('#exportJson').onclick=()=>download(JSON.stringify(brandData(),null,2),`${state.word}-brandbook.json`,'application/json');
  $$('.export-grid button').forEach(b=>b.onclick=()=>copy(b.dataset.export==='css'?cssVariables():b.dataset.export==='tailwind'?tailwindTokens():figmaTokens()));
  setTheme(state.theme);createSystem(state.word);renderHistory();if(location.hash)activateSection(location.hash.slice(1));
})();
